# Nixpacks Configuration for Railway
# This file tells Railway how to build and run your application

[phases.setup]
nixPkgs = ["nodejs-20_x", "postgresql"]

[phases.install]
cmds = [
  "cd backend && npm ci",
  "npx prisma generate"
]

[phases.build]
cmds = [
  "cd backend && npm run build"
]

[start]
cmd = "cd backend && npm start"

[staticAssets]
"public" = "/public"

[watchDirs]
"backend/src" = true
"backend/prisma" = true
