# Railway Configuration for iBit Repair
# https://railway.com/project/3b086c2b-00bf-4c87-9dba-810509613cca

[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build && npx prisma generate"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
